behaviors:
  KimchiRunBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 20488
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      memory:
        sequence_length: 128
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.1
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 10
    even_checkpoints: true
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 10000